### ISSUE TITLE
Support for embedded file description (`Desc` key)? 

### ISSUE THREAD

**Issue by petervwyatt** [metanorma/mn2pdf#278] opened 2024-09-06 03:55 UTC
mn2pdf now embeds files without any issues, however the display in PDF viewers only has a default description:

![image](https://github.com/user-attachments/assets/8ef0ddc9-33e3-400a-aef0-d63c4d33ab97)

Can I author in AsciiDoc replacement text for "[NO INFORMATION AVAILABLE]"? I don't see anything in the [documentation](https://www.metanorma.org/author/topics/sections/attachments/).

Ideally, I'd also like to set the `AFRelationship` value too, since in this use-case for ISO 32000-2 Amd1 my preference is for `Alternative` rather than the default of `Data` (as a default this fine).

And trying to think laterally for HTML output - maybe the `/Desc` is akin to `aria-label`? (see https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8)

**Comment by ronaldtse** [comment] 2024-09-06 04:39
Thanks @petervwyatt for raising this. 

Food for thought for @opoudjis @Intelligent2013

**Comment by Intelligent2013** [comment] 2024-09-06 10:40
> Ideally, I'd also like to set the `AFRelationship` value too, since in this use-case for ISO 32000-2 Amd1 my preference is for `Alternative` rather than the default of `Data` (as a default this fine).

Apache FOP supports only three properties:
- `filename`
- `src`
- `description`
```xml
<pdf:embedded-file filename="image.jpg" src="url(file:///C:/Temp/myimage.jpg)" description="My image"/>
```
Documentation: https://xmlgraphics.apache.org/fop/2.9/output.html#pdf-embedded-file
Source code: [`PDFEmbeddedFileAttachment.java`](https://github.com/apache/xmlgraphics-fop/blob/main/fop-core/src/main/java/org/apache/fop/render/pdf/extensions/PDFEmbeddedFileAttachment.java)

I'll add the attribute for `Relationship` data.

@opoudjis may we need to support this format for attachments? Example:
```
* [[[file1,attachment:(sources/program.c)]]],
span:description[Description text for program.c],
span:relationship[Alternative]
```

**Comment by ronaldtse** [comment] 2024-09-06 10:58
Here we run into a problem with defining attachments as bibliographic items. 

An attachment is more than a bibliographic item:
* it has a file path
* it does contain metadata for cross-references (i.e. it has a bibliographic item)
* it has additional metadata as shown in this case (description, alt, filename)

What proposed by @Intelligent2013 is possible, but it is not ideal, because:
* the `span:[...]` syntax is **only** intended for bibliographic items (these attributes are from the Relaton / ISO 690 data model)
* expanding the `span:[...]` syntax to support a different model (i.e. `description`, `relationship`) than Relaton is extremely confusing to the user.

**Comment by petervwyatt** [comment] 2024-09-06 14:13
@Intelligent2013 - apologies. Description does indeed work! I was viewing the help on my iPad and didn't notice the horizontal scroll! Thank you.

**Comment by petervwyatt** [comment] 2024-09-06 14:17
@ronaldtse I can live with hand-editing the **AFRelationship** values for ISO 32000-2:2020 Amd1 as there are only 2 embedded files, and it's a short amendment, so it's easy to locate the related text. But in the longer term, it would be good for ISO 32000-x:20xx as that will end up with far more.

**Comment by opoudjis** [comment] 2024-09-13 12:34
> Here we run into a problem with defining attachments as bibliographic items.
> 
> An attachment is more than a bibliographic item:
> 
> * it has a file path
> * it does contain metadata for cross-references (i.e. it has a bibliographic item)
> * it has additional metadata as shown in this case (description, alt, filename)

> What proposed by @Intelligent2013 is possible, but it is not ideal, because:
> 
> * the `span:[...]` syntax is **only** intended for bibliographic items (these attributes are from the Relaton / ISO 690 data model)
> * expanding the `span:[...]` syntax to support a different model (i.e. `description`, `relationship`) than Relaton is extremely confusing to the user.

Attachments are being modelled in Metanorma as bibliographic items. Which was always a legitimate option, because any readable asset can be modelled as a bibliographic item. And I am not going to discard the approach I took unless it becomes impossible to use. Metanorma is far too complicated and difficult to keep track of as is, without us undoing markup decisions as well.

So long as Metanorma models attachments as bibliographic items, then extensions to the bibliographic markup syntax to deal with PDF are not confusing, they are the POINT of that encoding. So I am going to have to make the call on whether these novel requirements can be accommodated in bibliographic markup or not. I agree (reluctantly) that the existing model of annotating bibliographies should not be extended arbitrarily to model PDF attachment attributes at the expense of the existing bibliographic model.

Of the three mentioned attributes, the filename is already addressed in the existing markup, so it is not an additional requirement. There remains the description can indeed by default be served as the  title or formatted content of the reference, which is what is in place now.

What  remains to be determined is, what the attributes that may need to be supported are. I am having difficulty making sense of ISO 32000-2, 7.11.3 and 7.11.4, but here goes:

Fixed values:

* 7. 11.3
  * Type is fixed as `Filespec`
  * FS is fixed as `URL`
   * ID has to be set by the PDF author

* 7.11.4 
  * Type is fixed as `EmbeddedFile`

Values inferred from the file itself:

* 7. 11.3
  * F is the filename of the file to be embedded; that is already marked up in the existing syntax as the document identifier, and there is no reason to pass it as a separate parameter. If there is, though, obviously there is a bibliographic metadata attribute for it, `/bibitem/uri` = `span:uri[]`. URIs in Relaton are intended as locators, after all, as distinct from `docidentifier`; the filename is a locator.
  * UF, as far is I can tell, is the full path name of the URI locator for the file, as opposed to F being the basename component of it. It is inferred as for F
  * DOS, Unix, Mac are deprecated platform-specific versions of UF
  * EF and RF seem to be somehow derived from F and UF
  * CI I do not understand, but it also seems to be some kind of collection of file descriptors

* 7.11.4 
  * Subtype is the MIME type, that is inferred from the OS metadata for the file
  * Params.Size  is inferred from the OS metadata for the file
  * Params.Checksum is inferred from the OS metadata for the file

Bibliographic values

* 7.11.3
  * Desc: All bibliographic items have descriptions, it's right in Dublin Core. The expedient solution, which already works is the preformatted reference supplied after the comma in source markup. The proper Relaton modelling for a description is `/bibitem/abstract`. `span:abstract[]` does not exist yet, but adding it is legitimate for Relaton.
  * An element corresponding to Thumb was recently added to Relaton, as `/bibitem/depiction`, containing an image (intended as a thumbnail of the bibliographic resource described). Since it is the only place an image occurs (or indeed can occur) in Relaton, I don't believe it needs novel markup: the presence of an inline image, image:[], in a bibliographic description should be taken as a depiction.
     * There is a dystopian future in which we might be tempted to add organisation logos to bibliographic entries. I think we should avoid that, and I also think that by default, an inline image in a citation should still be assumed to be a thumbnail. We may yet be forced to add `span:organization[Organisation name... image:[\] ]`, but that will not be PDF attachments' problem 
   
* 7.11.4 
  * Params.CreationDate, if not inferred from the OS metadata for the file, is `/bibitem/date[@type = `created`]`, marked up as `span:date.created[]`
  * Params.ModDate,  if not inferred from the OS metadata for the file, is `/bibitem/date[@type = `updated`]`, marked up as `span:date.updated[]`

Values not obviously bibliographic

* 7.11.3
  * V, the volatility flag, may need to be set on an ad-hoc basis (given what the document author knows about how much the file gets updated
  * If AFRelationship were actually modelling the relation of the bibliographic resource to the source, that would pose a problem: citations are only included for the purpose of citation, and nothing else is modelled for them. In fact, the relationship between two bibliographic resources *is* modelled in Relaton: it is `biblitem/relation[@type =...]/bibitem`; but the implicit relation of the bibitem itself is `citedIn`, and there is no obvious way of overriding that without either novel markup, or (somewhat too cleverly) `biblitem/relation[@type =...]/bibitem` somehow pointing back to the parent document.
    * The thing is though, AFRelationship is mostly actually encoding information about the resource: FormData, Schema, EncryptedPayload, Data appear to me to be inferred from the MIME type of the document, and @petervwyatt is proposing a default value for attachments anyway. It is only Alternative and Supplement that really seem to provide information about use and not format. And I think that information somehow aligns to Relaton's `/bibitem/medium`, although Medium is purposefully vague (https://www.relaton.org/model/medium/)
  * EP follows from AFRelationship = EncryptedPayload

There is one more rabbit up my sleeve though. Relaton provides for arbitrary classifications of bibliographical resources: https://www.relaton.org/model/additional-info/#classification . You can put Dewey numbers in there, but you can in fact put any key/value pair in there you want, by design. That seems a far simpler way of extending bibliographic descriptions, and indeed we are going to want that kind of key/value extensibility no matter how we encode attachments, because future requirements cannot be foreseen.

**Comment by opoudjis** [comment] 2024-09-13 12:41
So this is what I propose to do, to deal with attachment attributes with the existing bibliographic encoding.

Markup already supported:
* F, UF: nothing to add, already addressed with the URI being passed as the filepath of the attachment
* Desc: by default, if `/formattedref` is present for the bibliographic representation (the text after the comma), use that. 
* Params.CreationDate: use `span:date.created[]`
* Params.ModDate: use `span:date.updated[]`

Markup to be implemented:

* Desc: if `/formattedref` is not present for the bibliographic representation (the text after the comma), use `span:abstract[]`. 
* Thumb: use  `image:[]` **
* V: use `span:classification[pdf-volatile=true]` (we are going to make this a PDF-specific attribute)
* AFRelationship: use `span:classification[pdf-AFRelationship=EncryptedPayload] (ditto)

**Comment by petervwyatt** [comment] 2024-09-15 05:16
@opoudjis - you're becoming a PDF expert 😁

However I think we can also simplify a few things (of course, if you wish to keep these features for other output formats that is perfectly acceptable and shouldn't stop also having parallel support in PDF):

* see https://pdf-issues.pdfa.org/32000-2-2020/clause07.html#H7.11.3 for some spec corrections

* there is no need to support thumbnails as many viewers either ignore this or generate on the fly from content (this is because of past malicious use of thumbnails in tricking users into thinking that a file is of type A but is really type B)

* you don't need to support portable collections (a.k.a. portfolios) or encrypted wrappers - so you can ignore **CI**. I cannot see a need for publishing individual documents with these features. These would more likely be used by SDOs if they wished to do something fancy with packaging multiple standards documents.

* it's highly unlikely you'll need **RF** (related files array) - this is only if multiple files need to be kept together to functionally work. Such file formats are very rare. Ignore.

* ignore **V** - this only applies to external files, not embedded files.

* inside the **EF** sub-dictionary, just set **F** to be the simplified 7-bit ASCII version of the Unicode **UF** filename (both are needed for compliance, but since you're coming from Unicode this is the simplest method). This is pure ASCII, not UTF-8!!!! And you need to avoid paths, O/S specifics, etc. as PDF excludes these.

* **Params** is useful but not critical. It helps in workflows since the **Checksum** MD5 fingerprint shows if the file has been modified after creation. Please add if you can.

* **AFRelationship** is required for a machine-understandable semantic understanding of what the file represents (e.g. why it is embedded) - and it is needed for PDF/A-3, PDF/A-4 and PDF/UA-2 compliance. It will also be spoken aloud which helps users with disabilities. Relying on the filename or extension is insufficient - for example in ISO 32000 we will embed lots of PDFs - but some will be functional examples whereas others might be alternate data representations of data (e.g. Annex L).

Hope that helps.

**Comment by ronaldtse** [comment] 2024-09-15 10:18
Thanks @petervwyatt @opoudjis .

For the portfolio, I last saw the OIML use that. Their standards are delivered as a single document in a portfolio. 

Metanorma supports collections, so technically we could map our collections feature to the PDF portfolio when there is such request. 

For encryption, Metanorma PDF already supports that functionality via a presentational metadata. I'm not sure if it's well documented. 

With regards to using the bibliographic syntax for attachments, I remain of the view that we should not overload a bibliography entry with additional semantics that are not bibliography related. 

There is also a difficulty in using the attachments functionality with requiring the user to enter the same information twice (collection.yml and the bibliography), it also makes the whole thing unscalable. 

The simplest way to put this feature request is:
- when there is a single document with attachments, the collection.yml file should not be needed. The collection.yml file is only needed to tie more than one document together. 
- when there are attachments, there is a syntax that allows specification of them from within the document.

**Comment by opoudjis** [comment] 2024-09-16 02:08
Metanorma already supports single documents with attachments, without collection.yml, with specification within the document; that was implemented  months ago.

A extension of a bibliographic record is a much more sound basis for attachment metadata than a representation that will need to encode bibliographic information anyway, and will also need to add ad hoc information. Any markup solution will need to add ad hoc metadata. I will not hardcode metadata from PDF-A, ARIA, TEI, or RFC 1149 into a representation of attachments in Metanorma, and I will not add yet another piece of ad hoc markup to Metanorma, which is far too overloaded with ad hoc markup as is.

Streamlining collections is a completely separate issue, and there are going to be contexts where both bibliography and collection manifest are needed (when an attachment is cited). It may be possible to automatically add the bibliography, and it may be possible to encode the attachment internal to a document; but if an attachment is cited from multiple documents in the collection, and it can be, the existing markup convention will need to remain.

We are going to need to discuss this internally. Please reach out when available.

**Comment by petervwyatt** [comment] 2024-09-16 09:03
@ronaldtse 
> For the portfolio, I last saw the OIML use that. Their standards are delivered as a single document in a portfolio.

I can only assume they do this so they can add extra pages w/o actually modifying the PDF files. I certainly know a few NBs that insert their own front matter pages to the front of ISO PDFs (and also resize all pages!). But if you need it, so be it. Also note that some PDF 1.7 portfolio features were highly Adobe proprietary (such as SWF!) and are no longer supported by anyone. PDF 2.0 also standardized this is a much more open and vendor neutral manner.

**Comment by opoudjis** [comment] 2024-09-30 10:03
I am going to implement the behaviour I have described above, treating AFRelationship as a classification tag on a bibliographic entry for the attachment. We can introduce YAML syntax as a metanorma-extension, to describe attachments (although I continue not to see the point in it), but it can happen after the functionality is implemented the bibliographic way.

**Comment by opoudjis** [comment] 2024-10-07 10:43
We will implement `span:classification.key[value]`, by analogy with `span:uri[]` and `span:docid[]`, so:

* V: use `span:classification.pdf-volatile[true]`
* AFRelationship: `span:classification.pdf-AFRelationship[EncryptedPayload]`

**Comment by opoudjis** [comment] 2024-10-08 08:50
I'm closing this issue for now. We can revisit attachments encoding if we must, but this is giving us all the wherewithal we need to implement PDF attachment attributes.

**Closed by opoudjis** 2024-10-08 08:50 UTC
Labels: enhancement
